/*
* generated by Xtext
*/
package org.correttouml.grammars.ui.contentassist;

import org.correttouml.grammars.ui.contentassist.AbstractStateMachineActionsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class StateMachineActionsProposalProvider extends AbstractStateMachineActionsProposalProvider {

}
