/*
* generated by Xtext
*/
package org.correttouml.grammars;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class StateMachineTriggersUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.correttouml.grammars.ui.internal.StateMachineTriggersActivator.getInstance().getInjector("org.correttouml.grammars.StateMachineTriggers");
	}
	
}
