/*
* generated by Xtext
*/
package org.correttouml.grammars;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PropertyStandaloneSetup extends PropertyStandaloneSetupGenerated{

	public static void doSetup() {
		new PropertyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

