/*
* generated by Xtext
*/
package org.correttouml.grammars.ui.contentassist;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class StateMachineTriggersProposalProvider extends AbstractStateMachineTriggersProposalProvider {

}
