/*
 * generated by Xtext
 */
package org.correttouml.grammars.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StateMachineTriggersUiModule extends org.correttouml.grammars.ui.AbstractStateMachineTriggersUiModule {
	public StateMachineTriggersUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
