/*
 * generated by Xtext
 */
package org.correttouml.grammars;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StateMachineActionsRuntimeModule extends org.correttouml.grammars.AbstractStateMachineActionsRuntimeModule {

}
