/*
* generated by Xtext
*/
package org.correttouml.grammars.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class BooleanExpressionsOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
