/*
 * generated by Xtext
 */
package org.correttouml.grammars.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.correttouml.grammars.ui.internal.StateMachineTriggersActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StateMachineTriggersExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return StateMachineTriggersActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return StateMachineTriggersActivator.getInstance().getInjector(StateMachineTriggersActivator.ORG_CORRETTOUML_GRAMMARS_STATEMACHINETRIGGERS);
	}
	
}
