/*
* generated by Xtext
*/
package org.correttouml.grammars.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.correttouml.grammars.services.StateMachineTriggersGrammarAccess;

public class StateMachineTriggersParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private StateMachineTriggersGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.correttouml.grammars.parser.antlr.internal.InternalStateMachineTriggersParser createParser(XtextTokenStream stream) {
		return new org.correttouml.grammars.parser.antlr.internal.InternalStateMachineTriggersParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public StateMachineTriggersGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StateMachineTriggersGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
