/*
 * generated by Xtext
 */
package org.correttouml.grammars.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.correttouml.grammars.services.PropertyGrammarAccess;

public class PropertyParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PropertyGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.correttouml.grammars.parser.antlr.internal.InternalPropertyParser createParser(XtextTokenStream stream) {
		return new org.correttouml.grammars.parser.antlr.internal.InternalPropertyParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PropertyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PropertyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
