/*
* generated by Xtext
*/
package org.correttouml.grammars.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.correttouml.grammars.services.AssignmentsGrammarAccess;

public class AssignmentsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AssignmentsGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.correttouml.grammars.parser.antlr.internal.InternalAssignmentsParser createParser(XtextTokenStream stream) {
		return new org.correttouml.grammars.parser.antlr.internal.InternalAssignmentsParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public AssignmentsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AssignmentsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
