/*
 * generated by Xtext
 */
package org.correttouml.grammars.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractStateMachineActionsJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.correttouml.grammars.stateMachineActions.StateMachineActionsPackage.eINSTANCE);
		return result;
	}

}
