/*
 * generated by Xtext
 */
package org.correttouml.grammars.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StateMachineActionsUiModule extends org.correttouml.grammars.ui.AbstractStateMachineActionsUiModule {
	public StateMachineActionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
